### PR TITLE
fix: Avoid emitting redundant parentheses

### LINKED ISSUE #493: nightly failure with #[deny(unused_parens)], tuple tokens
see https://github.com/remexre/g1/runs/338256289#step:5:535

looks like it was broken by https://github.com/rust-lang/rust/pull/65112

### PR DESCRIPTION
**Pull request by Marwes**
Fixes #493

### CODE REVIEW

**Comment by brendanzab** [comment]
Yay, this is most appreciated! 👏

File: lalrpop/src/normalize/lower/mod.rs [hunk 1]
```diff
@@ -349,7 +352,15 @@ impl<'s> LowerState<'s> {
...
-                    "(<>)".to_string()
+                    let len = match &normalized_symbols {
+                        Symbols::Named(names) => names.len(),
+                        Symbols::Anon(indices) => indices.len(),
+                    };
+                    if len == 1 {
+                        "<>".to_string()
+                    } else {
+                        "(<>)".to_string()
+                    }
```
Comment (gabipurcaru) [inline lalrpop/src/normalize/lower/mod.rs]: nice! I was just trying to debug this warning and realised you've already fixed it :) this PR is really educational, thanks!
