### PR TITLE
Process escape sequences in string literals appearing as terminals.

### LINKED ISSUE #405: Escapes in string literals are broken
Characters escaped by backslashes are not handled properly in string literals. For example, the following grammar accepts strings of two backslashes, rather than strings of one backslash. There is no way to accept strings of one backslash using LALRPOP's built-in lexical analyzer generator.
```
grammar;

pub Expr: String = {
    <slash: "\\"> => slash.to_owned()
}
```
Internally, `Tokenizer::string_literal` parses that as `Tok::StringLiteral(r#"\\"#)` (in Rust syntax), which eventually makes its way to `lexer::re::parse_literal`, which then tries to escape it again, resulting in the regular expression `r#"\\\\"#`.

### PR DESCRIPTION
**Pull request by jimblandy**
The "\\" and "\"" escapes are necessary to make it possible to put arbitrary text in a string literal at all. We have to support "\t" and "\n" to compile the `whitespace` example from the book. But the other Rust escape sequences like "\u{2a}" don't really seem necessary.

Fixes #405.

### CODE REVIEW

File: lalrpop/src/tok/mod.rs [hunk 1]
```diff
@@ -736,3 +738,31 @@ fn is_identifier_start(c: char) -> bool {
...
+        let mut iter = code.char_indices();
+        let mut text = String::new();
+        while let Some((_, mut ch)) = iter.next() {
+            if ch == '\\' {
+                // The parser should never have accepted an ill-formed string
+                // literal, so we know it can't end in a backslash.
+                let (offset, next_ch) = iter.next().unwrap();
+                ch = match next_ch {
+                    '\\' | '\"' => next_ch,
+                    'n' => '\n',
```
Comment (Marwes) [inline lalrpop/src/tok/mod.rs]: `\r` seems fair to include as well as it shouldn't be to rare.

Comment (jimblandy) [reply lalrpop/src/tok/mod.rs]: Okay, that's implemented in bfa33d2.

**Comment by Marwes** [comment]
Sorry for the delay here. Thanks for the PR! I am going to try and do one hopefully small change and then release 0.16.1

**Comment by jimblandy** [comment]
Excellent! Really looking forward to the release. (I want to use \ as my lambda operator, like Haskell. :) )
